refactor: CHRUBY_VERSION → RUBY_VERSION

diff --git a/bin/with-chruby b/bin/with-chruby
--- a/bin/with-chruby
+++ b/bin/with-chruby
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-if [[ -z "${CHRUBY_VERSION}" ]]; then
-	echo "CHRUBY_VERSION not defined, aborting..." >&2
+if [[ -z "${RUBY_VERSION}" ]]; then
+	echo "RUBY_VERSION not defined, aborting..." >&2
 	exit 3
 fi
 
@@ -9,7 +9,7 @@ fi
 if [[ -n "${BASH}" || -n "${ZSH_NAME}" ]]; then
 	. /usr/local/share/chruby/chruby.sh
 	. /usr/local/share/chruby/auto.sh
-	chruby ${CHRUBY_VERSION}
+	chruby ${RUBY_VERSION}
 fi
 
 exec "$@"
