fix: better error handling

diff --git a/cat-which b/cat-which
--- a/cat-which
+++ b/cat-which
@@ -4,4 +4,10 @@
 # Finds full path to executable and displays the content.
 #
 
-cat `which $*`
+exec_="$@"
+
+if $(which "${exec_}" >/dev/null); then
+	cat $(which ${exec_})
+else
+	echo "${exec_} not found" >&2
+fi
